# Generated by Django 6.0 on 2025-12-27 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="gamescore",
            name="games_games_game_na_0c503d_idx",
        ),
        migrations.AlterField(
            model_name="gamescore",
            name="score_type",
            field=models.CharField(
                choices=[("LOW", "LOW"), ("HIGH", "HIGH")], default="LOW", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="gamescore",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
